"""
CSV Column Schema for Product Export

Defines the complete column structure based on the Swagify product template.
Contains 150+ columns for comprehensive product data export.
"""

# Complete list of CSV columns in order (from the Excel template)
CSV_COLUMNS = [
    "Swagify SKU",
    "Variant SKU",
    "Parent SKU",
    "Supplier SKU",
    "Source",
    "Active",
    "Primary Supplier",
    "Product Name",
    "Category-1",
    "Sub-Category-1-1",
    "Sub-Category-1-1-1",
    "Hex Color",
    "Fillers",
    "PMS Color Match",
    "Variant Type",
    "Print methods",
    "Long Description",
    "Country of Origin",
    "Inventory Quantity",
    "Inventory Location",
    "Material",
    "Size",
    "Location Name",
    "All Charges",
    "Brand",
    "Imprint Size",
    "Extra Color Run Charge",
    "Max Colors",
    "Max Included Colors",
    "Extra Stitches Charge",
    "Text Charges",
    "Imprint Color",
    "Rush Production Charges",
    "Setup Charge",
    "Running Charge",
    "Embroidery Upcharge for Additional stitches",
    "Minimum Order Qty",
    "QtyBreak1",
    "Price1",
    "QtyBreak2",
    "Price2",
    "QtyBreak3",
    "Price3",
    "QtyBreak4",
    "Price4",
    "QtyBreak5",
    "Price5",
    "QtyBreak6",
    "Price6",
    "QtyBreak7",
    "Price7",
    "QtyBreak8",
    "Price8",
    "QtyBreak9",
    "Price9",
    "QtyBreak10",
    "Price10",
    "QtyBreak11",
    "Price11",
    "QtyBreak12",
    "Price12",
    "QtyBreak13",
    "Price13",
    "QtyBreak14",
    "Price14",
    "QtyBreak15",
    "Price15",
    "QtyBreak16",
    "Price16",
    "Part Group",
    "Description",
    "Product Bows",
    "Product Options",
    "Package Length",
    "Package Width",
    "Package Height",
    "Package Weight",
    "1 imprint color name",
    "1 imprint color hex",
    "Custom color Code",
    "USA Production additional cost/unit",
    "Show Separatly",
    "Digital Proof Request",
    "Artwork Type",
    "Print Position",
    "Optional Carabiner",
    "Optional Lid",
    "Optional Straw",
    "Optional Main Image",
    "Gallery Images",
    "Ship Point | Zip",
    "Sage|ESP Setup|Repeat|Additional Color Setup Charge",
    "Sage|ESP Additional Color Run Charges",
    "Sage|ESP Price Includes",
    "Sage|ESP Imprint Method",
    "Sage|ESP Imprint Location",
    "Sage|ESP Product Pricing Code",
    "Sage|ESP Item Size",
    "Sage|ESP Personalization",
    "ESP Imprint Colors",
    "Compliance Certs",
    "Sage|ESP ESP Categories",
    "Sage Categories",
    "DC Categories",
    "Product Type",
    "Artwork Sold Unimprinted",
    "Sage Additional Field Information",
    "Imprint Area And Method Note",
    "Hot Stamp",
    "Hot Stamp2",
    "Need Pretreat",
    "Max Imprint Colors By Print Methods",
    "Print Area Width",
    "Print Area Height",
    "Front Or Back Print Area",
    "Sleeve Print Area",
    "Neck Label Print Area",
    "Epoxy Dome",
    "Hot Stamp Qrg",
    "Patch",
    "Sample Sku",
    "Cp Label",
    "Usa Prod Additional Cost Unit",
    "Iron On Backing",
    "Stick On Backing",
    "Hook And Loop Backing",
    "Plastic Backing",
    "Button Loop",
    "Metallic Thread Option",
    "Standard Imprint Colors",
    "Pre Production Repeat",
    "Shipping",
    "Tech Sheet",
    "Compliance Option2",
    "Title",
    "Capacity",
    "Blank No Blank",
    "Dec Multi Color Imprint",
    "Second Location Imprint",
    "Packaging",
    "Optional Gift Box",
    "Thread Colors",
    "Embroidery Pricing 3d",
    "Optional Patches",
    "Optional Imprint",
    "Approximate Size",
    "Color Change",
    "Second Imprint Area",
    "Third Imprint Area",
    "Fourth Imprint Area",
    "Imprint Method",
    "Item Details",
    "Theme",
    "Rush Service",
    "Rush Time",
    "Unique Product Number",
    "Apparel Style",
    "Apparel Imprint Includes",
    "Additional Notes Iv",
    "Additional Notes V",
    "Additional Notes Vi",
    "Additional Notes Vii",
    "Additional Notes Viii",
    "Compliance Info",
    "Item Weight",
    "Table Name",
    "Approximate Production Time",
    "Imprint Second Position",
    "Imprint Second Position Care Instructions",
    "Fob Zip",
    "Optional Laser Engraving",
    "Lifestyle Image",
    "Second Side Imprint",
    "Shipping Weight",
    "Hot Stamp Foil Colors",
    "Flavors",
    "Flavors Available",
    "Optional Canister",
    "Product Optional Dimensions",
    "Print Area Printed Mints",
    "Second Design Wrapper Colors",
    "Individual Drop Shipping",
    "Optional Stock Designs",
    "Label Size",
    "Lead Time",
    "Refills",
    "Optional Pen Tube",
    "Apply To Product",
    "Optional Woven Patch Information",
    "Non Woven Items",
    "Compatable Items",
    "Samples Optional",
    "Pen Mixing Charge",
    "Tape Charge",
    "Setup Charges Disc Code",
    "Running Charge Disc Code",
    "Imprint Charges",
    "Setup Charge Text",
    "Running Charge Text",
    "Re Order Setup Charge",
    "Individual Peronalization",
    "Item Packaging",
    "Item Packaging Detail",
    "Pack Method",
    "Template download",
    "Additional Infos",
]

# Column descriptions and expected data types
COLUMN_METADATA = {
    "Swagify SKU": {"type": "string", "description": "Unique Swagify identifier"},
    "Variant SKU": {"type": "string", "description": "SKU for product variant"},
    "Parent SKU": {"type": "string", "description": "Parent product SKU"},
    "Supplier SKU": {"type": "string", "description": "Supplier's product identifier"},
    "Source": {"type": "string", "description": "Source website/supplier name"},
    "Active": {"type": "boolean", "description": "Product active status"},
    "Primary Supplier": {"type": "string", "description": "Primary supplier name"},
    "Product Name": {"type": "string", "description": "Product display name"},
    "Category-1": {"type": "string", "description": "Main product category"},
    "Sub-Category-1-1": {"type": "string", "description": "First level subcategory"},
    "Sub-Category-1-1-1": {"type": "string", "description": "Second level subcategory"},
    "Hex Color": {"type": "string", "description": "Product color in hex format"},
    "Long Description": {"type": "string", "description": "Full product description"},
    "Material": {"type": "string", "description": "Product material"},
    "Size": {"type": "string", "description": "Product size"},
    "Minimum Order Qty": {"type": "integer", "description": "Minimum order quantity"},
}


def get_empty_row() -> dict:
    """Return a dictionary with all CSV columns set to empty string."""
    return {col: "" for col in CSV_COLUMNS}


def get_column_count() -> int:
    """Return the total number of columns."""
    return len(CSV_COLUMNS)
